### ISSUE TITLE
Evaluating the model

### ISSUE THREAD

**Issue by Moniruzzaman1988** [holmdk/Video-Prediction-using-PyTorch#1]
Hi, How do you evaluate this model?

**Comment by lifebl** [comment]
I used your model, but it didn't work very well. I used MSELOSS() and RMSE.

**Comment by holmdk** [comment]
I would probably need some more information on your setup, it could be related to different pytorch version, etc.   

Try and follow the guide from this [article](https://towardsdatascience.com/video-prediction-using-convlstm-with-pytorch-lightning-27b195fd21a2) and see if you can get it working.
