### ISSUE TITLE
missing data_loader

### ISSUE THREAD

**Issue by Kampmarsvin** [holmdk/Video-Prediction-using-PyTorch#2]
I get the following error when trying to run the main.py
  
File "main.py", line 127, in MovingMNISTLightning
    @pl.data_loader
AttributeError: module 'pytorch_lightning' has no attribute 'data_loader'

**Comment by holmdk** [comment]
Yes @pl.data_loader was removed in a new PyTorch lightning version.

Simply remover the decoraters "@pl.data_loader" from all dataloaders in the code and you should be fine!
