### ISSUE TITLE
using my own dataset

### ISSUE THREAD

**Issue by Singapore-mor** [holmdk/Video-Prediction-using-PyTorch#4]
Thanks for your great work! I wonder if  I want to use my dataset to train model, how to rewrite the dataloader？

**Comment by holmdk** [comment]
Thanks. You need to write a custom pytorch dataloader for this, which there are many guides for. Here is one from the [official documentation](https://pytorch.org/tutorials/beginner/data_loading_tutorial.html). Compare that to [my dataloader](https://github.com/holmdk/Video-Prediction-using-PyTorch/blob/master/data/MovingMNIST.py), and you should be able to see what to change to make it work for your own dataset hopefully.
