### ISSUE TITLE
Images size

### ISSUE THREAD

**Issue by yustiks** [holmdk/Video-Prediction-using-PyTorch#8]
Hello!
Thank you for the nice code.
Is it possible to change the input size of the images given to the network?
Let's say: not 64x64, but 200x100?
How the structure of the network should be changed?
Thank you for the answer in advance!

**Comment by holmdk** [comment]
The model is compatible with different image sizes, the width and height parameters are not altered by the model - only the number of feature maps in the various encoder and decoder layers. So, you do not necessarily need to change the structure of the network, although you might get better performance with more/less filters.
